services:


  ##-------------------------------------------##
  ##--------- Infrastructure Services ---------##
  ##-------------------------------------------##

  keplereum-config-server:
    build: ./ConfigServer
    container_name: keplereum-config-server
    ports:
      - "8888:8080"
    environment:
      SPRING_PROFILES_ACTIVE: native
    networks:
      - keplereum-microservices-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 30s

  keplereum-discovery-server:
    build: ./DiscoveryServer
    container_name: keplereum-discovery-server
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CLOUD_CONFIG_URI: http://keplereum-config-server:8888
    depends_on:
      keplereum-config-server:
        condition: service_healthy
    networks:
      - keplereum-microservices-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 30s

  keplereum-api-gateway:
    build: ./apiGateway
    container_name: keplereum-api-gateway
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CLOUD_CONFIG_URI: http://keplereum-config-server:8888
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://keplereum-discovery-server:8761/eureka
    depends_on:
      keplereum-discovery-server:
        condition: service_healthy
    networks:
      - keplereum-microservices-net


  ##---------------------------------------##
  ##--------- Main Micro-Services ---------##
  ##---------------------------------------##


  keplereum-user-groundstation-service:
    build: ./User_GroundStation_Service
    container_name: keplereum-user-groundstation-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CLOUD_CONFIG_URI: http://keplereum-config-server:8888
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://keplereum-discovery-server:8761/eureka
    depends_on:
      - keplereum-config-server
      - keplereum-discovery-server
      - keplereum-user-db
    networks:
      - keplereum-microservices-net

  keplereum-blockchain-service:
    build: ./Blockchain_Service
    container_name: keplereum-blockchain-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CLOUD_CONFIG_URI: http://keplereum-config-server:8888
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://keplereum-discovery-server:8761/eureka
    depends_on:
      - keplereum-config-server
      - keplereum-discovery-server
      - keplereum-blockchain-db
    networks:
      - keplereum-microservices-net

  keplereum-satellites-service:
    build: ./Satellites_Service
    container_name: keplereum-satellites-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CLOUD_CONFIG_URI: http://keplereum-config-server:8888
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://keplereum-discovery-server:8761/eureka

    depends_on:
      - keplereum-config-server
      - keplereum-discovery-server
      - keplereum-satellite-db
    networks:
      - keplereum-microservices-net

  ##------------------------------------##
  ##---------Services DataBases---------##
  ##------------------------------------##

  keplereum-user-db:

    image: postgres
    container_name: keplereum-user-db
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user
    ports:
      - "5432:5432"
    volumes:
      - keplereum-user-data:/var/lib/postgresql/data
    networks:
      - keplereum-microservices-net


  keplereum-satellite-db:
    image: postgres
    container_name: keplereum-satellite-db
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: satellite
    ports:
      - "5433:5432"
    volumes:
      - keplereum-satellite-data:/var/lib/postgresql/data
    networks:
      - keplereum-microservices-net

  keplereum-blockchain-db:
    image: postgres
    container_name: keplereum-blockchain-db
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blockchain
    ports:
      - "5434:5432"
    volumes:
      - keplereum-blockchain-data:/var/lib/postgresql/data
    networks:
      - keplereum-microservices-net

  ##------------------------------------------------------------------##
  ##----------------- Zipkin (for flow monitoring) -------------------##
  ##------------------------------------------------------------------##
  keplereum-zipkin:
    container_name: keplereum-zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"


  keplereum-prometheus:
    container_name: keplereum-prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - keplereum-microservices-net
    depends_on:
      - keplereum-user-service
      - keplereum-blockchain-service
      - keplereum-satellites-service

  keplereum-grafana:
    container_name: keplereum-grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin123
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - keplereum-microservices-net
    depends_on:
      - keplereum-prometheus


volumes:
  keplereum-user-data:
  keplereum-satellite-data:
  keplereum-blockchain-data:
  prometheus-data:
  grafana-data:

networks:
  keplereum-microservices-net:
    driver: bridge