services:

  ##-------------------------------------------##
  ##--------- Infrastructure Services ---------##
  ##-------------------------------------------##

  keplereum-config-server:
    build: ./ConfigServer
    container_name: keplereum-config-server
    ports:
      - "8888:8080"
    networks:
      - keplereum-microservices-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 30s

  keplereum-discovery-server:
    build: ./DiscoveryServer
    container_name: keplereum-discovery-server
    ports:
      - "8761:8761"
    environment:
      SPRING_CLOUD_CONFIG_URI: http://keplereum-config-server:8888
    depends_on:
      keplereum-config-server:
        condition: service_healthy
    networks:
      - keplereum-microservices-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 30s

  keplereum-api-gateway:
    build: ./apiGateway
    container_name: keplereum-api-gateway
    ports:
      - "8080:8080"
    environment:
      SPRING_CLOUD_CONFIG_URI: http://keplereum-config-server:8888
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://keplereum-discovery-server:8761/eureka
    depends_on:
      keplereum-discovery-server:
        condition: service_healthy
    networks:
      - keplereum-microservices-net

  ##---------------------------------------##
  ##--------- Main Micro-Services ---------##
  ##---------------------------------------##

  
  keplereum-user-service:
    links:
      - keplereum-zipkin
    build: ./User_GroundStation_Service
    container_name: keplereum-user-groundstation-service
    environment:
      JAVA_TOOL_OPTIONS: >-
        -Dspring.zipkin.base-url=http://keplereum-zipkin:9411
        -Dspring.zipkin.sender.type=web
        -Dmanagement.tracing.enabled=true
      SPRING_ZIPKIN_BASE_URL: http://keplereum-zipkin:9411
      SPRING_ZIPKIN_ENDPOINT: http://keplereum-zipkin:9411/api/v2/spans
      MANAGEMENT_ZIPKIN_BASE_URL: http://keplereum-zipkin:9411
      MANAGEMENT_TRACING_ENDPOINT: http://keplereum-zipkin:9411/api/v2/spans
      SPRING_CLOUD_CONFIG_OVERRIDESYSTEMPROPERTIES: "false"
      SPRING_ZIPKIN_ENABLED: "true"
      SPRING_SLEUTH_SAMPLER_PROBABILITY: "1.0"
      SPRING_CLOUD_CONFIG_URI: http://keplereum-config-server:8888
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://keplereum-discovery-server:8761/eureka
    depends_on:
      - keplereum-config-server
      - keplereum-discovery-server
      - keplereum-user-db
      - keplereum-zipkin
    networks:
      - keplereum-microservices-net

  keplereum-blockchain-service:
    links:
      - keplereum-zipkin
    build: ./Blockchain_Service
    container_name: keplereum-blockchain-service
    environment:
      JAVA_TOOL_OPTIONS: >-
        -Dspring.zipkin.base-url=http://keplereum-zipkin:9411
        -Dspring.zipkin.sender.type=web
        -Dmanagement.tracing.enabled=true
      SPRING_ZIPKIN_BASE_URL: http://keplereum-zipkin:9411
      SPRING_ZIPKIN_ENABLED: "true"
      SPRING_SLEUTH_SAMPLER_PROBABILITY: "1.0"
      SPRING_CLOUD_CONFIG_URI: http://keplereum-config-server:8888
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://keplereum-discovery-server:8761/eureka
    depends_on:
      - keplereum-config-server
      - keplereum-discovery-server
      - keplereum-blockchain-db
      - keplereum-zipkin
    networks:
      - keplereum-microservices-net

  keplereum-satellites-service:
    links:
      - keplereum-zipkin
    build: ./Satellites_Service
    container_name: keplereum-satellites-service
    environment:
      JAVA_TOOL_OPTIONS: >-
        -Dspring.zipkin.base-url=http://keplereum-zipkin:9411
        -Dspring.zipkin.sender.type=web
        -Dmanagement.tracing.enabled=true
      SPRING_ZIPKIN_BASE_URL: http://keplereum-zipkin:9411
      SPRING_ZIPKIN_ENABLED: "true"
      SPRING_SLEUTH_SAMPLER_PROBABILITY: "1.0"
      SPRING_CLOUD_CONFIG_URI: http://keplereum-config-server:8888
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://keplereum-discovery-server:8761/eureka

    depends_on:
      - keplereum-config-server
      - keplereum-discovery-server
      - keplereum-satellite-db
      - keplereum-zipkin
    networks:
      - keplereum-microservices-net

  ##------------------------------------##
  ##---------Services DataBases---------##
  ##------------------------------------##

  keplereum-user-db:
    image: postgres
    container_name: keplereum-user-db
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user
    ports:
      - "5432:5432"
    volumes:
      - keplereum-user-data:/var/lib/postgresql/data
    networks:
      - keplereum-microservices-net

  keplereum-satellite-db:
    image: postgres
    container_name: keplereum-satellite-db
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: satellite
    ports:
      - "5433:5432"
    volumes:
      - keplereum-satellite-data:/var/lib/postgresql/data
    networks:
      - keplereum-microservices-net

  keplereum-blockchain-db:
    image: postgres
    container_name: keplereum-blockchain-db
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blockchain
    ports:
      - "5434:5432"
    volumes:
      - keplereum-blockchain-data:/var/lib/postgresql/data
    networks:
      - keplereum-microservices-net

  ##------------------------------------------------------------------##
  ##----------------- Zipkin (for flow monitoring) -------------------##
  ##------------------------------------------------------------------##
  keplereum-zipkin:
    container_name: keplereum-zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - keplereum-microservices-net

volumes:
  keplereum-user-data:
  keplereum-satellite-data:
  keplereum-blockchain-data:

networks:
  keplereum-microservices-net:
    name: keplereum-microservices-net 
    driver: bridge