scrape_configs:
  - job_name: 'eureka-service'
    metrics_path: '/actuator/prometheus'
    eureka_sd_configs:
      - server: 'http://localhost:8761/eureka'
    relabel_configs:
      - source_labels: [__meta_eureka_app_name]
        target_label: service
