apiVersion: apps/v1
kind: Deployment
metadata:
  name: satellites-service
  labels:
    app: satellites-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: satellites-service
  template:
    metadata:
      labels:
        app: satellites-service
    spec:
      containers:
        - name: satellites-service
          image: keplereum/satellites-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8070

---
apiVersion: v1
kind: Service
metadata:
  name: satellites-service-svc
spec:
  ports:
    - targetPort: 8070
      port: 80
  selector:
    app: satellites-service