## Satellites Service DB StatefulSet Deployement / K8s Service ##
#################################################################

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: satellites-db
  labels:
    app: satellites-db
spec:
  serviceName: "satellites-db"
  replicas: 1
  selector:
    matchLabels:
      app: satellites-db
  template:
    metadata:
      labels:
        app: satellites-db
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: satellites_user
            - name: POSTGRES_PASSWORD
              value: satellites_password
            - name: POSTGRES_DB
              value: satellites
          volumeMounts:
            - name: satellites-db-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: satellites-db-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: satellites-db-svc
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: satellites-db

---

## Satellites Service Deployement / K8s Service ##
############### Satellites Service ###############

apiVersion: apps/v1
kind: Deployment
metadata:
  name: satellites-service
  labels:
    app: satellites-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: satellites-service
  template:
    metadata:
      labels:
        app: satellites-service
    spec:
      containers:
        - name: satellites-service
          image: keplereum/satellites-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8070
          env:
            - name: CONFIG_SERVER_URL
              value: http://config-server:8888
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://satellites-db-svc:5432/satellites
            - name: SPRING_DATASOURCE_USERNAME
              value: satellites_user
            - name: SPRING_DATASOURCE_PASSWORD
              value: satellites_password
---
apiVersion: v1
kind: Service
metadata:
  name: satellites-service-svc
spec:
  ports:
    - targetPort: 8070
      port: 80
  selector:
    app: satellites-service