global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']


  - job_name: 'keplereum-api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['keplereum-api-gateway:8222']
    scrape_interval: 10s

  - job_name: 'keplereum-user-groundstation-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['keplereum-user-groundstation-service:8090']
    scrape_interval: 10s

  - job_name: 'keplereum-blockchain-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['keplereum-blockchain-service:8091']
    scrape_interval: 10s

  - job_name: 'keplereum-satellites-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['keplereum-satellites-service:8070']
    scrape_interval: 10s


  # Zipkin metrics (if available)
  - job_name: 'keplereum-zipkin'
    static_configs:
      - targets: ['keplereum-zipkin:9411']
    scrape_interval: 30s
    metrics_path: '/prometheus'