eureka:
  instance:
    hostname: keplereum-discovery-server
  client:
    service-url:
      defaultzone: http://keplereum-discovery-server:8761/eureka
    registerWithEureka: true
    fetchRegistry: true


server:
  port: 8091

spring:
  application:
    name: BLOCKCHAIN-SERVICE

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://keplereum-blockchain-db:5434/blockchain
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

management:
  tracing:
    sampling:
      probability: 1.0