eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://eureka-0.eureka.default.svc.cluster.local:8761/eureka}

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: user-route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/groundstations/**, /api/v1/users/**

        - id: sattelite-route
          uri: lb://SATELLITE-SERVICE
          predicates:
            - Path=/api/v1/satellites/**, /api/v1/models/**, /api/v1/trajectories/**, /api/v1/sensors/**

        - id: Blockchain-route
          uri: lb://BLOCKCHAIN-SERVICE
          predicates:
            - Path=/api/v1/blocks/**, /api/v1/transactions/**, /api/v1/nodes/**, /api/v1/blockchain/**



  application:
    name: GATEWAY

server:
  port: 8222

management:
  tracing:
    sampling:
      probability: 1.0