eureka:
  client:
    serviceUrl:
      defaultZone: http://keplereum-discovery-server:8761/eureka
    registerWithEureka: true
    fetchRegistry: true

server:
  port: 8090

spring:
  application:
    name: keplereum-user-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://keplereum-user-db:5432/user
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  zipkin:
    base-url: http://keplereum-zipkin:9411
    enabled: true

  sleuth:
    sampler:
      probability: 1.0

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99
      sla:
        http.server.requests: 10ms, 100ms
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
    zipkin:
      endpoint: http://keplereum-zipkin:9411/api/v2/spans
  zipkin:
    tracing:
      endpoint: http://keplereum-zipkin:9411/api/v2/spans
