logging:
  level:
    root: INFO
    com.example: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: DEBUG
spring:
  application:
    name: GATEWAY
  config:
    import: optional:configserver:http://localhost:8888

