server:
  port: 8888

spring:
  profiles:
    active: native
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
      overrideSystemProperties: true
      
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

