server:
  port: 8888

spring:
  profiles:
    active: native
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        native:
            search-locations: classpath:/configurations

management:
  endpoints:
    web:
      exposure:
        include: health,info  # /actuator/health and /actuator/info
  endpoint:
    health:
      show-details: always